language: php
sudo: false
dist: trusty

env:
  global:
    - RUN_PHPCS="no"
    - RUN_SCRUTINIZER="no"
    - COMPOSER_FLAGS="--prefer-stable"
    - PHPUNIT_FLAGS=""

matrix:
  fast_finish: true
  include:
    - php: 7.0
    - php: 7.0
      env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest"
    - php: 7.0
      env: RUN_PHPCS="yes"
    - php: 7.1
    - php: 7.1
      # This empty flag removes the prefer-stable switch to cause dev dependencies to be installed
      env: COMPOSER_FLAGS=""
    - php: 7.2
    - php: nightly
  allow_failures:
    - php: 7.2
    - php: nightly

before_script:
  - composer self-update
  - composer update $COMPOSER_FLAGS

script:
  - if [ "$RUN_SCRUTINIZER" == "yes" ]; then mkdir -p .travis/logs; fi;
  - vendor/bin/phpunit $PHPUNIT_FLAGS
  - if [ "$RUN_SCRUTINIZER" == "yes" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi;
  - if [ "$RUN_SCRUTINIZER" == "yes" ]; then php ocular.phar code-coverage:upload --format=php-clover .travis/logs/clover.xml; fi;
  - if [ "$RUN_PHPCS" == "yes" ]; then vendor/bin/phpcs -p --report=full --extensions=php --standard=PSR2 src/; fi;
